/*
 * Compile-time compatibility checks for the physical WHIRL operator layout.
 */

#include "defs.h"
#include "opcode_gen_core.h"

#define CHECK_OPERATOR_VALUE(name, value) \
    typedef char check_##name[(name == value) ? 1 : -1]

CHECK_OPERATOR_VALUE(OPERATOR_UNKNOWN, 0);
CHECK_OPERATOR_VALUE(OPERATOR_FIRST, 1);
CHECK_OPERATOR_VALUE(OPR_ABS, 1);
CHECK_OPERATOR_VALUE(OPR_XPRAGMA, 126);
CHECK_OPERATOR_VALUE(OPR_AFFIRM, 127);
CHECK_OPERATOR_VALUE(OPR_ALLOCA, 128);
CHECK_OPERATOR_VALUE(OPR_DEALLOCA, 129);
CHECK_OPERATOR_VALUE(OPR_LDMA, 130);
CHECK_OPERATOR_VALUE(OPR_ASM_STMT, 131);
CHECK_OPERATOR_VALUE(OPR_ASM_EXPR, 132);
CHECK_OPERATOR_VALUE(OPR_ASM_INPUT, 133);
CHECK_OPERATOR_VALUE(OPR_RROTATE, 134);
CHECK_OPERATOR_VALUE(OPR_LDA_LABEL, 135);
CHECK_OPERATOR_VALUE(OPR_GOTO_OUTER_BLOCK, 136);
CHECK_OPERATOR_VALUE(OPR_EXTRACT_BITS, 137);
CHECK_OPERATOR_VALUE(OPR_COMPOSE_BITS, 138);
CHECK_OPERATOR_VALUE(OPR_SHUFFLE, 145);

#if defined(TARG_X8664)
CHECK_OPERATOR_VALUE(OPR_REPLICATE, 139);
CHECK_OPERATOR_VALUE(OPR_REDUCE_ADD, 140);
CHECK_OPERATOR_VALUE(OPR_REDUCE_MPY, 141);
CHECK_OPERATOR_VALUE(OPR_REDUCE_MAX, 142);
CHECK_OPERATOR_VALUE(OPR_REDUCE_MIN, 143);
CHECK_OPERATOR_VALUE(OPR_PURE_CALL_OP, 144);
CHECK_OPERATOR_VALUE(OPR_ATOMIC_RSQRT, 146);
CHECK_OPERATOR_VALUE(OPR_ZDLBR, 147);
#elif defined(TARG_MIPS)
CHECK_OPERATOR_VALUE(OPR_PURE_CALL_OP, 139);
#if defined(TARG_SL)
CHECK_OPERATOR_VALUE(OPR_SL2_FORK_MAJOR, 140);
CHECK_OPERATOR_VALUE(OPR_SL2_FORK_MINOR, 141);
CHECK_OPERATOR_VALUE(OPR_ZDLBR, 142);
#else
CHECK_OPERATOR_VALUE(OPR_ZDLBR, 140);
#endif
#elif defined(KEY)
#if defined(TARG_LOONGSON)
CHECK_OPERATOR_VALUE(OPR_MPYU2, 139);
CHECK_OPERATOR_VALUE(OPR_MPYI2, 140);
CHECK_OPERATOR_VALUE(OPR_PURE_CALL_OP, 141);
CHECK_OPERATOR_VALUE(OPR_ZDLBR, 142);
#else
CHECK_OPERATOR_VALUE(OPR_PURE_CALL_OP, 139);
CHECK_OPERATOR_VALUE(OPR_ZDLBR, 140);
#endif
#else
CHECK_OPERATOR_VALUE(OPR_ZDLBR, 139);
#endif

CHECK_OPERATOR_VALUE(OPR_DSL, 148);
CHECK_OPERATOR_VALUE(OPERATOR_LAST, 148);

typedef char check_OPC_MDSL
    [(OPC_MDSL == OPR_DSL + (MTYPE_M << 8) + (MTYPE_V << 14)) ? 1 : -1];

int
main(void)
{
    return 0;
}
