#!/bin/csh -f
#
#  Copyright (C) 2008 PathScale, LLC.  All Rights Reserved.
#
#  Copyright (C) 2000, 2001 Silicon Graphics, Inc.  All Rights Reserved.
#
#  This program is free software; you can redistribute it and/or modify it
#  under the terms of version 2 of the GNU General Public License as
#  published by the Free Software Foundation.
#
#  This program is distributed in the hope that it would be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
#
#  Further, this software is distributed without any warranty that it is
#  free of the rightful claim of any third person regarding infringement 
#  or the like.  Any license provided herein, whether implied or 
#  otherwise, applies only to this software file.  Patent licenses, if 
#  any, provided herein do not apply to combinations of this program with 
#  other software, or any other product whatsoever.  
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write the Free Software Foundation, Inc., 59
#  Temple Place - Suite 330, Boston MA 02111-1307, USA.
#
#  Contact information:  Silicon Graphics, Inc., 1600 Amphitheatre Pky,
#  Mountain View, CA 94043, or:
#
#  http://www.sgi.com
#
#  For further information regarding this notice, see:
#
#  http://oss.sgi.com/projects/GenInfo/NoticeExplan
#
#

### ====================================================================
### ====================================================================
###
### Module: gen_opsch_set
### $Revision$
### $Date$
### $Author$
### $Source$
### Revision history:
###   21-Feb-2008 - Original version
###
### Usage:      gen_opsch_set utildir opts
###
###     Generate the opsch_set.[ch] module.  'Utildir' is where to
###     find the gen_x_set stuff. 'Opts' is passed as teh first
###     argument to gen_x_set to allow specification of functional or
###     macro interfaces.
###
###     We do this in a file so the make
###     rule can depend on it and the modules can be rebuilt when the
###     procedure changes
###
### ====================================================================
### ====================================================================


perl $1/gen_x_set $2 opsch_set 'OPSCH*' OPSCH_SET OPSCH_id OPSCHvec     \
                           'defs.h'                                     \
                           'mempool.h'                                  \
		    	   'hb_sched.h'
