/*
 * Copyright (C) 2021 Xcalibyte (Shenzhen) Limited.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_xcalibyte_BGenDriver */

#ifndef _Included_io_xcalibyte_BGenDriver
#define _Included_io_xcalibyte_BGenDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    bgenInit
 * Signature: (ZII)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_bgenInit
  (JNIEnv *, jclass, jboolean, jint, jint);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    bgenInitOpenIrFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_bgenInitOpenIrFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    bgenInitSetDST
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_bgenInitSetDST
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    bgenFileClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_bgenFileClose
  (JNIEnv *, jclass);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    bgenFileFinish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_bgenFileFinish
  (JNIEnv *, jclass);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    getPrimitiveType
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_getPrimitiveType
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    setTypeAttribute
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_setTypeAttribute
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    setTypePuAttribute
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_setTypePuAttribute
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    createFunctionType
 * Signature: (J[JI)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_createFunctionType
  (JNIEnv *, jclass, jlong, jlongArray, jint);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    createClassType
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_createClassType
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    createRefType
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_createRefType
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    allocateSpotInClass
 * Signature: (JLjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_allocateSpotInClass
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniMakePointerType
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniMakePointerType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    setMiscFlags
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_setMiscFlags
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    createArrayType
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_createArrayType
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    finalizeFields
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_finalizeFields
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    printTypeInfo
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_printTypeInfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    getTySize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_getTySize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniSetFldBaseClass
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_jniSetFldBaseClass
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    setTyAlign
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_setTyAlign
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    getTyAlign
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_xcalibyte_BGenDriver_getTyAlign
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    createCommonArrayType
 * Signature: (JJIJJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_createCommonArrayType
  (JNIEnv *, jclass, jlong, jlong, jint, jlong, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    setArbUbd
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_setArbUbd
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniSetFldType
 * Signature: (JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniSetFldType
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniGetCurrentFieldIdx
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniGetCurrentFieldIdx
  (JNIEnv *, jclass);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniSetFldAsPointer
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniSetFldAsPointer
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    setFileRbc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_setFileRbc
  (JNIEnv *, jclass);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    setFileVTable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_setFileVTable
  (JNIEnv *, jclass);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    setPuLangCXX
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_setPuLangCXX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    setPuLangC
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_setPuLangC
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    setPuLangJava
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_setPuLangJava
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    setPuConstructor
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_setPuConstructor
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    setPuNoReturn
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_setPuNoReturn
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    setPuIsMainPu
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_setPuIsMainPu
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    clearPuIsInlie
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_clearPuIsInlie
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    setPuNoInline
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_setPuNoInline
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    setCurrPuRbc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_setCurrPuRbc
  (JNIEnv *, jclass);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    createFunctionSymbol
 * Signature: (Ljava/lang/String;JIII)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_createFunctionSymbol
  (JNIEnv *, jclass, jstring, jlong, jint, jint, jint);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    createExternFunctionSymbol
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_createExternFunctionSymbol
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    bindFunctionParams
 * Signature: ([JJJ)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_bindFunctionParams
  (JNIEnv *, jclass, jlongArray, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    createVarSymbol
 * Signature: (Ljava/lang/String;JIII)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_createVarSymbol
  (JNIEnv *, jclass, jstring, jlong, jint, jint, jint);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    setVTable
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_setVTable
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    setClassSymbol
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_setClassSymbol
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    setClassCopyCtor
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_setClassCopyCtor
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    createPregSymbol
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_createPregSymbol
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    createPreg
 * Signature: (ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_createPreg
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    getStPtr
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_getStPtr
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    printSymbolInfo
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_printSymbolInfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    initializeWithArray
 * Signature: ([JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_initializeWithArray
  (JNIEnv *, jclass, jlongArray, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    getReturnValPreg
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_getReturnValPreg
  (JNIEnv *, jclass);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniCreateBlock
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniCreateBlock
  (JNIEnv *, jclass);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniCreateRegion
 * Signature: (IJJJI)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniCreateRegion
  (JNIEnv *, jclass, jint, jlong, jlong, jlong, jint);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniMapTabCreate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniMapTabCreate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniPoolInitialize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniPoolInitialize
  (JNIEnv *, jclass);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniNewScope
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniNewScope
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniSetLineNum
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_jniSetLineNum
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniGetLineNum
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_xcalibyte_BGenDriver_jniGetLineNum
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniSetCurrentSrcFile
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_jniSetCurrentSrcFile
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniCreateIf
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniCreateIf
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniCreateTrueBr
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniCreateTrueBr
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniCreateFalseBr
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniCreateFalseBr
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniInsertBlockFirst
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_jniInsertBlockFirst
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniInsertBlockLast
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_jniInsertBlockLast
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniInsertBlockBefore
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_jniInsertBlockBefore
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniInsertBlockAfter
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_jniInsertBlockAfter
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniGetParentBlock
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniGetParentBlock
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniLDA
 * Signature: (IJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniLDA
  (JNIEnv *, jclass, jint, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniLDID
 * Signature: (IJJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniLDID
  (JNIEnv *, jclass, jint, jlong, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniLDIDField
 * Signature: (IJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniLDIDField
  (JNIEnv *, jclass, jint, jlong, jlong, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniSTID
 * Signature: (IJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniSTID
  (JNIEnv *, jclass, jint, jlong, jlong, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniILoad
 * Signature: (IJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniILoad
  (JNIEnv *, jclass, jint, jlong, jlong, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniIStore
 * Signature: (IJJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniIStore
  (JNIEnv *, jclass, jint, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniSTIDField
 * Signature: (IJJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniSTIDField
  (JNIEnv *, jclass, jint, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    getBodyFromEntry
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_getBodyFromEntry
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    getPointeeTyFromTY
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_getPointeeTyFromTY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    getTyFromST
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_getTyFromST
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    getRtypeFromWN
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_xcalibyte_BGenDriver_getRtypeFromWN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    getMTypeFromTypeIdx
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_xcalibyte_BGenDriver_getMTypeFromTypeIdx
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniCreateBinary
 * Signature: (IJJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniCreateBinary
  (JNIEnv *, jclass, jint, jlong, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniCreateUnary
 * Signature: (IJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniCreateUnary
  (JNIEnv *, jclass, jint, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniCreateTernary
 * Signature: (IJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniCreateTernary
  (JNIEnv *, jclass, jint, jlong, jlong, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniIntConst
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniIntConst
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniFloatConst
 * Signature: (ID)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniFloatConst
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniCreateReturn
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniCreateReturn
  (JNIEnv *, jclass);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniCreateReturnVal
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniCreateReturnVal
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    funcICall
 * Signature: (JJIJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_funcICall
  (JNIEnv *, jclass, jlong, jlong, jint, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    printWN
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_printWN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    intTypeConversion
 * Signature: (JB)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_intTypeConversion
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    floatTypeConversion
 * Signature: (JB)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_floatTypeConversion
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    typeConversion
 * Signature: (JB)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_typeConversion
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniIlda
 * Signature: (IIIIJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniIlda
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniExtractBits
 * Signature: (IIJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniExtractBits
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniParm
 * Signature: (IJJI)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniParm
  (JNIEnv *, jclass, jint, jlong, jlong, jint);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniAsmInput
 * Signature: (Ljava/lang/String;IJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniAsmInput
  (JNIEnv *, jclass, jstring, jint, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniAlloca
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniAlloca
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniComma
 * Signature: (IIJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniComma
  (JNIEnv *, jclass, jint, jint, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniRcomma
 * Signature: (IIJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniRcomma
  (JNIEnv *, jclass, jint, jint, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniRelational
 * Signature: (IIJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniRelational
  (JNIEnv *, jclass, jint, jint, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniLabel
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniLabel
  (JNIEnv *, jclass);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniCreateGoto
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniCreateGoto
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    getLabelNum
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_getLabelNum
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniCreateSwitch
 * Signature: (IJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniCreateSwitch
  (JNIEnv *, jclass, jint, jlong, jlong, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniCreateCasegoto
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniCreateCasegoto
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniCall
 * Signature: (IIIJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniCall
  (JNIEnv *, jclass, jint, jint, jint, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniArray
 * Signature: (J[JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniArray
  (JNIEnv *, jclass, jlong, jlongArray, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniSetWNKid
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_jniSetWNKid
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniSetCallFlag
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_jniSetCallFlag
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    mtypeToPreg
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_mtypeToPreg
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniOpcodeMakeOp
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_io_xcalibyte_BGenDriver_jniOpcodeMakeOp
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniCreateIntrinsic
 * Signature: (III[J)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniCreateIntrinsic
  (JNIEnv *, jclass, jint, jint, jint, jlongArray);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    startFunction
 * Signature: (JJII)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_startFunction
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    finishFunction
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_finishFunction
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniNewInito
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniNewInito
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    outputTrace
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_outputTrace
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniInitEHSym
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_jniInitEHSym
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniGetExecPtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniGetExecPtr
  (JNIEnv *, jclass);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniBuildEHBegin
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_jniBuildEHBegin
  (JNIEnv *, jclass);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniBuildTryCatch
 * Signature: (JJJ[J[J)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniBuildTryCatch
  (JNIEnv *, jclass, jlong, jlong, jlong, jlongArray, jlongArray);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniBuildEHEnd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_jniBuildEHEnd
  (JNIEnv *, jclass);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniSetupRegionInito
 * Signature: (JJJ[J)V
 */
JNIEXPORT void JNICALL Java_io_xcalibyte_BGenDriver_jniSetupRegionInito
  (JNIEnv *, jclass, jlong, jlong, jlong, jlongArray);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    jniBuildEHRegion
 * Signature: (JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_jniBuildEHRegion
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    getTryComparator
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_getTryComparator
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    saveAsTempString
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_saveAsTempString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    saveAsTempByteArray
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_io_xcalibyte_BGenDriver_saveAsTempByteArray
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     io_xcalibyte_BGenDriver
 * Method:    getStringUTF8Length
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_xcalibyte_BGenDriver_getStringUTF8Length
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
