/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jetbrains_java_decompiler_modules_bgen_BGenDriver */

#ifndef _Included_org_jetbrains_java_decompiler_modules_bgen_BGenDriver
#define _Included_org_jetbrains_java_decompiler_modules_bgen_BGenDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jetbrains_java_decompiler_modules_bgen_BGenDriver
 * Method:    bgenInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_java_decompiler_modules_bgen_BGenDriver_bgenInit
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_jetbrains_java_decompiler_modules_bgen_BGenDriver
 * Method:    bgenFinish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_java_decompiler_modules_bgen_BGenDriver_bgenFinish
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
