/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Define to 1 if the elf64_getehdr function is in libelf.a. */
#define HAVE_ELF64_GETEHDR 1

/* Define to 1 if the Elf64_Rel structure has r_info field. */
#define HAVE_ELF64_R_INFO 1

/* Define to 1 if you have the <elf.h> header file. */
#if defined(BUILD_OS_DARWIN)
#undef HAVE_ELF_H
#else /* defined(BUILD_OS_DARWIN) */
#define HAVE_ELF_H 1
#endif /* defined(BUILD_OS_DARWIN) */

/* Define to 1 if you have the <getopt.h> header file. */
#define HAVE_GETOPT_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <libelf.h> header file. */
#if defined(BUILD_OS_DARWIN)
#undef HAVE_LIBELF_H
#else /* defined(BUILD_OS_DARWIN) */
#define HAVE_LIBELF_H 1
#endif /* defined(BUILD_OS_DARWIN) */

/* Define to 1 if you have the <libelf/libelf.h> header file. */
#if defined(BUILD_OS_DARWIN)
#undef HAVE_LIBELF_LIBELF_H
#else /* defined(BUILD_OS_DARWIN) */
/* #undef HAVE_LIBELF_LIBELF_H */
#endif /* defined(BUILD_OS_DARWIN) */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <sgidefs.h> header file. */
/* #undef HAVE_SGIDEFS_H */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* See if __uint32_t is predefined in the compiler. */
/* #undef HAVE___UINT32_T */

/* Define 1 if sys/types.h defines __uint32_t. */
#define HAVE___UINT32_T_IN_SYS_TYPES_H 1

/* See if __uint64_t is predefined in the compiler. */
/* #undef HAVE___UINT64_T */

/* Define to header that first defines elf. */
#define LOCATION_OF_LIBELFHEADER <elf.h>

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1
