/*

  Copyright (C) 2000, 2001 Silicon Graphics, Inc.  All Rights Reserved.

  This program is free software; you can redistribute it and/or modify it
  under the terms of version 2 of the GNU General Public License as
  published by the Free Software Foundation.

  This program is distributed in the hope that it would be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

  Further, this software is distributed without any warranty that it is
  free of the rightful claim of any third person regarding infringement 
  or the like.  Any license provided herein, whether implied or 
  otherwise, applies only to this software file.  Patent licenses, if 
  any, provided herein do not apply to combinations of this program with 
  other software, or any other product whatsoever.  

  You should have received a copy of the GNU General Public License along
  with this program; if not, write the Free Software Foundation, Inc., 59
  Temple Place - Suite 330, Boston MA 02111-1307, USA.

  Contact information:  Silicon Graphics, Inc., 1600 Amphitheatre Pky,
  Mountain View, CA 94043, or:

  http://www.sgi.com

  For further information regarding this notice, see:

  http://oss.sgi.com/projects/GenInfo/NoticeExplan

*/


/* This file was automatically generated by f90generate.pl */

      INTRN_F4EXPONENT ,
      INTRN_FIRST_F90_INTRINSIC = INTRN_F4EXPONENT,
      INTRN_F8EXPONENT ,
      INTRN_FQEXPONENT ,
      INTRN_F4FRACTION ,
      INTRN_F8FRACTION ,
      INTRN_FQFRACTION ,
      INTRN_F4MODULO ,
      INTRN_F8MODULO ,
      INTRN_FQMODULO ,
      INTRN_F4NEAREST ,
      INTRN_F8NEAREST,
	INTRN_FQNEAREST ,
	INTRN_F4RRSPACING ,
	INTRN_F8RRSPACING ,
	INTRN_FQRRSPACING ,
	INTRN_F4SCALE ,
	INTRN_F8SCALE ,
	INTRN_FQSCALE ,
	INTRN_F4SET_EXPONENT ,
	INTRN_F8SET_EXPONENT ,
	INTRN_FQSET_EXPONENT ,
	INTRN_F4SPACING ,
	INTRN_F8SPACING ,
	INTRN_FQSPACING ,
	INTRN_F4NEXTAFTER ,
	INTRN_F8NEXTAFTER ,
	INTRN_FQNEXTAFTER ,
	INTRN_F4ISNAN ,
	INTRN_F8ISNAN ,
	INTRN_FQISNAN ,
	INTRN_F4SCALB ,
	INTRN_F8SCALB ,
	INTRN_FQSCALB ,
	INTRN_F4IEEE_REMAINDER ,
	INTRN_F8IEEE_REMAINDER ,
	INTRN_FQIEEE_REMAINDER ,
	INTRN_F4LOGB ,
	INTRN_F8LOGB ,
	INTRN_FQLOGB ,
	INTRN_F4ILOGB ,
	INTRN_F8ILOGB ,
	INTRN_FQILOGB ,
	INTRN_F4FPCLASS ,
	INTRN_F8FPCLASS ,
	INTRN_FQFPCLASS ,
	INTRN_F4FINITE ,
	INTRN_F8FINITE ,
	INTRN_FQFINITE ,
	INTRN_F4UNORDERED ,
	INTRN_F8UNORDERED ,
	INTRN_FQUNORDERED ,
	INTRN_I1POPCNT ,
	INTRN_I2POPCNT ,
	INTRN_I4POPCNT ,
	INTRN_I8POPCNT ,
	INTRN_I1LEADZ ,
	INTRN_I2LEADZ ,
	INTRN_I4LEADZ ,
	INTRN_I8LEADZ ,
	INTRN_LENTRIM ,
	INTRN_F90INDEX ,
	INTRN_SCAN ,
	INTRN_VERIFY ,
	INTRN_ADJUSTL ,
	INTRN_ADJUSTR ,
	INTRN_GET_IEEE_EXCEPTIONS ,
	INTRN_GET_IEEE_INTERRUPTS ,
	INTRN_GET_IEEE_ROUNDING_MODE ,
	INTRN_GET_IEEE_STATUS ,
	INTRN_SET_IEEE_EXCEPTIONS ,
	INTRN_SET_IEEE_EXCEPTION ,
	INTRN_SET_IEEE_INTERRUPTS ,
	INTRN_SET_IEEE_ROUNDING_MODE ,
	INTRN_SET_IEEE_STATUS ,
	INTRN_ENABLE_IEEE_INTERRUPT ,
	INTRN_DISABLE_IEEE_INTERRUPT ,
	INTRN_TEST_IEEE_EXCEPTION ,
	INTRN_TEST_IEEE_INTERRUPT ,
	INTRN_MATMUL ,
	INTRN_SPREAD ,
	INTRN_RESHAPE ,
	INTRN_TRANSPOSE ,
	INTRN_ALL ,
	INTRN_ANY ,
	INTRN_COUNT ,
	INTRN_PRODUCT ,
	INTRN_SUM ,
	INTRN_EOSHIFT ,
	INTRN_MAXVAL ,
	INTRN_MINVAL ,
	INTRN_MAXLOC ,
	INTRN_MINLOC ,
	INTRN_CSHIFT ,
	INTRN_DOT_PRODUCT,
	INTRN_PACK,
	INTRN_UNPACK,
	INTRN_MERGE,
	INTRN_CHAR,

	INTRN_LAST_F90_INTRINSIC = INTRN_CHAR,
