/*
 * Copyright 2004 PathScale, Inc.  All Rights Reserved.
 */

/*

  Copyright (C) 2000, 2001, Silicon Graphics, Inc.  All Rights Reserved.

  This program is free software; you can redistribute it and/or modify it
  under the terms of version 2.1 of the GNU Lesser General Public License 
  as published by the Free Software Foundation.

  This program is distributed in the hope that it would be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

  Further, this software is distributed without any warranty that it is
  free of the rightful claim of any third person regarding infringement 
  or the like.  Any license provided herein, whether implied or 
  otherwise, applies only to this software file.  Patent licenses, if
  any, provided herein do not apply to combinations of this program with 
  other software, or any other product whatsoever.  

  You should have received a copy of the GNU Lesser General Public 
  License along with this program; if not, write the Free Software 
  Foundation, Inc., 59 Temple Place - Suite 330, Boston MA 02111-1307, 
  USA.

  Contact information:  Silicon Graphics, Inc., 1600 Amphitheatre Pky,
  Mountain View, CA 94043, or:

  http://www.sgi.com

  For further information regarding this notice, see:

  http://oss.sgi.com/projects/GenInfo/NoticeExplan

*/

#include <stdlib.h>


#pragma ident "@(#) libf/fio/main.c	92.1	11/16/99 15:43:33"
/*
 * Use main to get to the MAIN__ entry point generated by the
 * Fortran 90 compiler on mips and on some little endian systems.
 * In the future, do not use the libF77 routine with Fortran 90.
 */
#if     defined(__linux) || defined(BUILD_OS_DARWIN)
extern void MAIN__(void);

extern void __f90_set_args(int argc, char **argv);

int __f90_main(int argc, char **argv, char **arge)
{
	__f90_set_args(argc, argv);
	
        MAIN__();
        exit(0);
        return (0);
}

#ifdef PATHSCALE_MERGE
typeof(__f90_main) main __attribute__((weak, alias("__f90_main")));
#endif

#endif
